# Generated by Django 3.0.2 on 2020-07-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserve_Date', models.DateField()),
                ('Reserve_Dayes', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Capacity', models.IntegerField()),
                ('Room_Price', models.IntegerField()),
                ('Room_type', models.CharField(max_length=50)),
                ('Room_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Room_About', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Fname', models.CharField(max_length=30)),
                ('User_Lname', models.CharField(max_length=50)),
                ('User_Mobile', models.CharField(max_length=11)),
                ('User_Phone', models.IntegerField()),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Gender', models.CharField(max_length=10)),
                ('User_BirthDay', models.DateField()),
            ],
        ),
    ]
